### ISSUE TITLE
Bug in getting target element from partial cfi `epubcfi(/4)`

### ISSUE THREAD

**Issue by hrishikesh-kadam** [readium/readium-cfi-js#72]
#### Expected Behaviour
[CFI.zip](https://github.com/readium/readium-cfi-js/files/2505724/CFI.zip)
In above zip, please find ch03.xhtml, I have written a test() function on click of its body.
getCfiFromNode() works as expected but in below function - 

```javascript
function getTargetNodeFromCfi() {

    var cfi = "epubcfi(/4)";
    //var cfi = "epubcfi(/4/4)";

    var $node;
    try {
        $node = EPUBcfi.Interpreter.getTargetElementWithPartialCFI(cfi, document);
    } catch (e) {
        console.error("-> getTargetNodeFromCfi -> " + e.stack);
    }

    console.log($node);
}
```

It should return me `body` element.
I want to fetch `body` element from the content document (partial) cfi.

#### Observed behaviour

throws following error - 

```javascript
getTargetNodeFromCfi -> SyntaxError: Expected "!/", ",", "/", "[", or [0-9] but ")" found.
    at peg$buildStructuredError (/CFI/readium-cfi.umd.js:12047:13)
    at peg$parse (/CFI/readium-cfi.umd.js:13088:12)
    at Object.getTargetElementWithPartialCFI (/CFI/readium-cfi.umd.js:13512:17)
    at getTargetNodeFromCfi (/CFI/bridge.js:21:37)
    at test (/CFI/bridge.js:4:5)
    at HTMLBodyElement.onclick (/CFI/ch03.xhtml:317:8)
```

#### Steps to reproduce
As explained above

#### Test file(s)
[CFI.zip](https://github.com/readium/readium-cfi-js/files/2505724/CFI.zip)

Fetched the readium-cfi-js files from https://github.com/readium/readium-cfi-js/tree/c1aaeed075f2720ac16c3056e224dcfddf46c520/dist folder

### Product

Other - Integrating cfi in FolioReader-Android

#### Additional information

I am aware of the partial cfi not being part of the http://www.idpf.org/epub/linking/cfi/epub-cfi.html specs but am I doing something wrong?

**Comment by danielweck** [comment]
Thanks for reporting!
The bug is here:

https://github.com/readium/readium-cfi-js/blob/be152d7bcf8295cfcde70b6e55134211cafab1c1/src/parser.pegjs#L55-L59
( https://github.com/readium/readium-cfi-js/blob/develop/src/parser.pegjs#L55-L59 )

`localPathVal:local_path` should be optional (append `?`) in the PEG grammar, and the returned object should account for this in its corresponding property value, for example `localPath:localPathVal` => `localPath:localPathVal?A:B`. By the way, this applies to other PEG rules as well, such as `localPath:localPathVal?localPathVal:""` which should return an object not a string, see:
https://github.com/readium/readium-cfi-js/blob/be152d7bcf8295cfcde70b6e55134211cafab1c1/src/parser.pegjs#L49-L53
( https://github.com/readium/readium-cfi-js/blob/develop/src/parser.pegjs#L49-L53 )

Now, the main problem with such change in the PEG grammar is that the "client side" of the API created by the parser-generator must also be updated to account for returned object types, and potential `null` / `undefined` values, see:

https://github.com/readium/readium-cfi-js/blob/be152d7bcf8295cfcde70b6e55134211cafab1c1/src/interpreter.js#L56-L65
( https://github.com/readium/readium-cfi-js/blob/develop/src/interpreter.js#L56-L65 )

(note how there is no sanity/nil check on `CFIAST.cfiString.localPath.steps.length `!)

As @jccr and I discussed recently, the ideal path forward would be to refactor the PEG grammar, make support for the `epubcfi()` scheme optional (this currently requires the initial EPUB package.opf spine indirection, but this is not really used anywhere internally in Readium, so a `doc-cfi()` scheme would make a lot more sense), clean up the "duplicate" / redundant rules, and update the API "client" code (such as the aforementioned "interpreter" logical layer).

**Comment by jccr** [comment]
I have a fix :)
Going to prepare and push to develop now.

**Comment by jccr** [comment]
@danielweck I managed to formulate a change to the grammar that doesn't require a client side fix. The test suites we looked at together are passing, in addition to the new test just for this case.

**Comment by jccr** [comment]
Here's the fix for anyone eager to get something working without waiting for my wider-scoped PR(#71) to be merged in:
https://github.com/readium/readium-cfi-js/pull/71/commits/4a9a83bd3de3bcfef81091575fa1de0bd166e398

**Comment by hrishikesh-kadam** [comment]
Thanks @jccr and @danielweck, eagerly waiting for this fix to get merged in master.

**Comment by hrishikesh-kadam** [comment]
Btw I just got to know that every method in this lib works with partial cfi.
You just have to prepend partial cfi with "/0!" as packageDocumentCFIComponent to use it as partial cfi.
Is that right?

So now `EPUBcfi.Interpreter.getTargetElement("epubcfi(/0!/4)", document)` does return `body` element.

**Comment by danielweck** [comment]
That was fixed in https://github.com/readium/readium-cfi-js/pull/71
